export const GET_LICENSE_REQUEST = 'GET_LICENSE_REQUEST';
export const GET_LICENSE_SUCCESS = 'GET_LICENSE_SUCCESS';
export const GET_LICENSE_ERROR = 'GET_LICENSE_ERROR';

export const UPDATE_LICENSE_REQUEST = 'UPDATE_LICENSE_REQUEST';
export const UPDATE_LICENSE_SUCCESS = 'UPDATE_LICENSE_SUCCESS';
export const UPDATE_LICENSE_ERROR = 'UPDATE_LICENSE_ERROR';

export const ADD_LICENSE_REQUEST = 'ADD_LICENSE_REQUEST';
export const ADD_LICENSE_SUCCESS = 'ADD_LICENSE_SUCCESS';
export const ADD_LICENSE_ERROR = 'ADD_LICENSE_ERROR';
