export const GET_SQUAD_REQUEST = 'GET_SQUAD_REQUEST';
export const GET_SQUAD_SUCCESS = 'GET_SQUAD_SUCCESS';
export const GET_SQUAD_ERROR = 'GET_SQUAD_ERROR';

export const GET_TEAM_REQUEST = 'GET_TEAM_REQUEST';
export const GET_TEAM_SUCCESS = 'GET_TEAM_SUCCESS';
export const GET_TEAM_ERROR = 'GET_TEAM_ERROR';
